// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Instances struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Type        string         `json:"type"`
	Status      string         `json:"status"`
	EfsPath     string         `json:"efs_path"`
	TaskArn     sql.NullString `json:"task_arn"`
	ContainerIp sql.NullString `json:"container_ip"`
	TtlHours    int32          `json:"ttl_hours"`
	LastActive  time.Time      `json:"last_active"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Users struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
