// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Instances struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Type           string         `json:"type"`
	Status         string         `json:"status"`
	EfsPath        string         `json:"efs_path"`
	VscodeTaskArn  sql.NullString `json:"vscode_task_arn"`
	VscodeIp       sql.NullString `json:"vscode_ip"`
	JupyterTaskArn sql.NullString `json:"jupyter_task_arn"`
	JupyterIp      sql.NullString `json:"jupyter_ip"`
	TtlHours       int32          `json:"ttl_hours"`
	LastActive     time.Time      `json:"last_active"`
	CreatedAt      time.Time      `json:"created_at"`
	TaskArn        sql.NullString `json:"task_arn"`
	ContainerIp    sql.NullString `json:"container_ip"`
}

type Users struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
